"""add_email_tracking_fields_to_communications

Revision ID: 3c0301b8fb05
Revises: c8f9d2e3a1b4
Create Date: 2025-12-03 20:44:39.624358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c0301b8fb05'
down_revision = 'c8f9d2e3a1b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new fields to communications table for email tracking
    op.add_column('communications', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('communications', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communications', 'opened_at')
    op.drop_column('communications', 'received_at')
    # ### end Alembic commands ###