"""Add dynamic phone/email fields for comma-delimited data explosion

Revision ID: 0dd017b57074
Revises: 09ca703105c1
Create Date: 2025-11-09 23:17:20.592293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0dd017b57074'
down_revision = '09ca703105c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('direct_number_2', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('direct_number_2_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('direct_number_3', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('direct_number_3_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('direct_number_4', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('direct_number_4_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('direct_number_5', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('direct_number_5_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('mobile_phone_2', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('mobile_phone_2_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('mobile_phone_3', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('mobile_phone_3_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('mobile_phone_4', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('mobile_phone_4_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('mobile_phone_5', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('mobile_phone_5_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('personal_phone_2', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('personal_phone_2_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('personal_phone_3', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('personal_phone_3_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('personal_phone_4', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('personal_phone_4_dnc', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('personal_phone_5', sa.String(length=20), nullable=True))
    op.add_column('contacts', sa.Column('personal_phone_5_dnc', sa.Boolean(), nullable=True))
    # Convert company_revenue to integer, setting NULL for unconvertible values
    op.execute("UPDATE contacts SET company_revenue = NULL WHERE company_revenue IS NOT NULL AND company_revenue !~ '^[0-9]+$'")
    op.alter_column('contacts', 'company_revenue',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='CASE WHEN company_revenue ~ \'^[0-9]+$\' THEN company_revenue::integer ELSE NULL END')
    op.alter_column('contacts', 'creation_source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('contacts', 'utm_source',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('contacts', 'utm_medium',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('idx_contacts_company_industry', table_name='contacts')
    op.drop_index('idx_contacts_company_name', table_name='contacts')
    op.drop_index('idx_contacts_creation_source', table_name='contacts')
    op.drop_index('idx_contacts_job_title', table_name='contacts')
    op.drop_index('idx_contacts_lead_score', table_name='contacts')
    op.drop_index('idx_contacts_overflow_data_gin', table_name='contacts', postgresql_using='gin')
    op.drop_index('idx_contacts_personal_zip', table_name='contacts')
    op.drop_index('idx_contacts_provider_uuid', table_name='contacts')
    op.drop_index('idx_contacts_utm_campaign', table_name='contacts')
    op.drop_index('ix_contacts_email_unique', table_name='contacts', postgresql_where='(email IS NOT NULL)')
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.alter_column('field_visibility', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_visibility', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_field_visibility_category', 'field_visibility', ['field_category'], unique=False)
    op.create_index(op.f('ix_field_visibility_field_name'), 'field_visibility', ['field_name'], unique=True)
    op.alter_column('users', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'approved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'deactivated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_users_is_approved', table_name='users')
    op.drop_index('idx_users_single_active_owner', table_name='users', postgresql_where="((role = 'owner'::user_role) AND (is_active = true))")
    op.create_index('idx_user_approved', 'users', ['is_approved'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_approved'), 'users', ['is_approved'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_approved'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index('idx_user_approved', table_name='users')
    op.create_index('idx_users_single_active_owner', 'users', ['role'], unique=True, postgresql_where="((role = 'owner'::user_role) AND (is_active = true))")
    op.create_index('idx_users_is_approved', 'users', ['is_approved'], unique=False)
    op.alter_column('users', 'deactivated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'approved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_field_visibility_field_name'), table_name='field_visibility')
    op.drop_index('idx_field_visibility_category', table_name='field_visibility')
    op.alter_column('field_visibility', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('field_visibility', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.create_index('ix_contacts_email_unique', 'contacts', ['email'], unique=True, postgresql_where='(email IS NOT NULL)')
    op.create_index('idx_contacts_utm_campaign', 'contacts', ['utm_campaign'], unique=False)
    op.create_index('idx_contacts_provider_uuid', 'contacts', ['provider_uuid'], unique=False)
    op.create_index('idx_contacts_personal_zip', 'contacts', ['personal_zip'], unique=False)
    op.create_index('idx_contacts_overflow_data_gin', 'contacts', ['overflow_data'], unique=False, postgresql_using='gin')
    op.create_index('idx_contacts_lead_score', 'contacts', ['lead_score'], unique=False)
    op.create_index('idx_contacts_job_title', 'contacts', ['job_title'], unique=False)
    op.create_index('idx_contacts_creation_source', 'contacts', ['creation_source'], unique=False)
    op.create_index('idx_contacts_company_name', 'contacts', ['company_name'], unique=False)
    op.create_index('idx_contacts_company_industry', 'contacts', ['company_industry'], unique=False)
    op.alter_column('contacts', 'utm_medium',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('contacts', 'utm_source',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('contacts', 'creation_source',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contacts', 'company_revenue',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('contacts', 'personal_phone_5_dnc')
    op.drop_column('contacts', 'personal_phone_5')
    op.drop_column('contacts', 'personal_phone_4_dnc')
    op.drop_column('contacts', 'personal_phone_4')
    op.drop_column('contacts', 'personal_phone_3_dnc')
    op.drop_column('contacts', 'personal_phone_3')
    op.drop_column('contacts', 'personal_phone_2_dnc')
    op.drop_column('contacts', 'personal_phone_2')
    op.drop_column('contacts', 'mobile_phone_5_dnc')
    op.drop_column('contacts', 'mobile_phone_5')
    op.drop_column('contacts', 'mobile_phone_4_dnc')
    op.drop_column('contacts', 'mobile_phone_4')
    op.drop_column('contacts', 'mobile_phone_3_dnc')
    op.drop_column('contacts', 'mobile_phone_3')
    op.drop_column('contacts', 'mobile_phone_2_dnc')
    op.drop_column('contacts', 'mobile_phone_2')
    op.drop_column('contacts', 'direct_number_5_dnc')
    op.drop_column('contacts', 'direct_number_5')
    op.drop_column('contacts', 'direct_number_4_dnc')
    op.drop_column('contacts', 'direct_number_4')
    op.drop_column('contacts', 'direct_number_3_dnc')
    op.drop_column('contacts', 'direct_number_3')
    op.drop_column('contacts', 'direct_number_2_dnc')
    op.drop_column('contacts', 'direct_number_2')
    # ### end Alembic commands ###
